# Generated by Django 5.2.18 on 2026-10-09 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="creado"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="activo"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=80, unique=True, verbose_name="identificador"
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="título")),
                (
                    "summary",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="resumen"
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("manual", "Manual de usuario"),
                            ("faq", "Preguntas frecuentes"),
                            ("permissions", "Roles y permisos"),
                            ("reference", "Referencia técnica"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="sección",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="orden"),
                ),
                (
                    "content",
                    models.TextField(blank=True, verbose_name="contenido (Markdown)"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="editado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "página de documentación",
                "verbose_name_plural": "páginas de documentación",
                "ordering": ["section", "order", "title"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="DocRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="registrado"
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("content", models.TextField(blank=True)),
                (
                    "edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="docs.docpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "revisión de documentación",
                "verbose_name_plural": "revisiones de documentación",
                "ordering": ["-created_at", "-id"],
                "default_permissions": (),
            },
        ),
    ]
