# Generated by Django 5.2.18 on 2026-10-09 15:34

import apps.core.fields
import apps.core.uploads
import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="creado"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="activo"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ej.: Sub 12",
                        max_length=60,
                        unique=True,
                        verbose_name="nombre",
                    ),
                ),
                (
                    "max_age",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(99)],
                        verbose_name="tope de edad",
                    ),
                ),
                (
                    "birth_year_limit",
                    models.PositiveSmallIntegerField(
                        help_text="Año de nacimiento mínimo permitido (nacidos en este año o después).",
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="tope de año de nacimiento",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "categoría",
                "verbose_name_plural": "categorías",
                "ordering": ["birth_year_limit", "name"],
            },
        ),
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="creado"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="activo"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=120, verbose_name="nombres"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=120, verbose_name="apellidos"),
                ),
                (
                    "phone",
                    apps.core.fields.EncryptedCharField(
                        blank=True,
                        default="",
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Teléfono inválido. Ejemplo: +58 412-1234567",
                                regex="^\\+?\\d[\\d\\s-]{6,18}$",
                            )
                        ],
                        verbose_name="teléfono",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.core.uploads.UploadTo("photos"),
                        validators=[apps.core.validators.validate_image_upload],
                        verbose_name="foto",
                    ),
                ),
                (
                    "vat_id",
                    models.CharField(
                        choices=[
                            ("V", "V - Venezolano"),
                            ("E", "E - Extranjero"),
                            ("J", "J - Jurídico"),
                            ("G", "G - Gubernamental"),
                        ],
                        default="V",
                        max_length=1,
                        verbose_name="tipo de documento",
                    ),
                ),
                (
                    "vat_number",
                    apps.core.fields.EncryptedCharField(
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El número de documento debe contener solo dígitos (5 a 9).",
                                regex="^\\d{5,9}$",
                            )
                        ],
                        verbose_name="número de documento",
                    ),
                ),
                (
                    "vat_hash",
                    models.CharField(
                        editable=False, max_length=64, null=True, unique=True
                    ),
                ),
                (
                    "document_photo",
                    models.FileField(
                        blank=True,
                        upload_to=apps.core.uploads.UploadTo("documents/identity"),
                        validators=[apps.core.validators.validate_document_upload],
                        verbose_name="foto del documento",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(max_length=60, verbose_name="licencia"),
                ),
                (
                    "license_photo",
                    models.FileField(
                        blank=True,
                        upload_to=apps.core.uploads.UploadTo("documents/licenses"),
                        validators=[apps.core.validators.validate_document_upload],
                        verbose_name="foto de licencia",
                    ),
                ),
                (
                    "license_expiry_year",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="año de vencimiento de licencia",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "entrenador",
                "verbose_name_plural": "entrenadores",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Delegate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="creado"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="activo"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=120, verbose_name="nombres"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=120, verbose_name="apellidos"),
                ),
                (
                    "phone",
                    apps.core.fields.EncryptedCharField(
                        blank=True,
                        default="",
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Teléfono inválido. Ejemplo: +58 412-1234567",
                                regex="^\\+?\\d[\\d\\s-]{6,18}$",
                            )
                        ],
                        verbose_name="teléfono",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.core.uploads.UploadTo("photos"),
                        validators=[apps.core.validators.validate_image_upload],
                        verbose_name="foto",
                    ),
                ),
                (
                    "vat_id",
                    models.CharField(
                        choices=[
                            ("V", "V - Venezolano"),
                            ("E", "E - Extranjero"),
                            ("J", "J - Jurídico"),
                            ("G", "G - Gubernamental"),
                        ],
                        default="V",
                        max_length=1,
                        verbose_name="tipo de documento",
                    ),
                ),
                (
                    "vat_number",
                    apps.core.fields.EncryptedCharField(
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El número de documento debe contener solo dígitos (5 a 9).",
                                regex="^\\d{5,9}$",
                            )
                        ],
                        verbose_name="número de documento",
                    ),
                ),
                (
                    "vat_hash",
                    models.CharField(
                        editable=False, max_length=64, null=True, unique=True
                    ),
                ),
                (
                    "document_photo",
                    models.FileField(
                        blank=True,
                        upload_to=apps.core.uploads.UploadTo("documents/identity"),
                        validators=[apps.core.validators.validate_document_upload],
                        verbose_name="foto del documento",
                    ),
                ),
                (
                    "license_status",
                    models.CharField(
                        choices=[
                            ("endorsed", "Avalado"),
                            ("not_endorsed", "No avalado"),
                        ],
                        default="not_endorsed",
                        max_length=20,
                        verbose_name="licencia",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delegate_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "delegado",
                "verbose_name_plural": "delegados",
                "ordering": ["last_name", "first_name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="creado"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="activo"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Venezuela", max_length=80, verbose_name="país"
                    ),
                ),
                ("state", models.CharField(max_length=80, verbose_name="estado")),
                (
                    "municipality",
                    models.CharField(max_length=120, verbose_name="municipio"),
                ),
                ("address", models.CharField(max_length=255, verbose_name="dirección")),
                ("name", models.CharField(max_length=120, verbose_name="nombre")),
                (
                    "manager_name",
                    models.CharField(max_length=160, verbose_name="responsable"),
                ),
                (
                    "manager_phone",
                    apps.core.fields.EncryptedCharField(
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Teléfono inválido. Ejemplo: +58 412-1234567",
                                regex="^\\+?\\d[\\d\\s-]{6,18}$",
                            )
                        ],
                        verbose_name="teléfono del responsable",
                    ),
                ),
                (
                    "length_m",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="largo / alto (m)",
                    ),
                ),
                (
                    "width_m",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="ancho (m)",
                    ),
                ),
                (
                    "is_divisible",
                    models.BooleanField(default=False, verbose_name="divisible"),
                ),
                (
                    "mini_fields_count",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(16),
                        ],
                        verbose_name="cantidad de mini canchas",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "cancha",
                "verbose_name_plural": "canchas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="creado"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="activo"
                    ),
                ),
                (
                    "vat_id",
                    models.CharField(
                        choices=[
                            ("V", "V - Venezolano"),
                            ("E", "E - Extranjero"),
                            ("J", "J - Jurídico"),
                            ("G", "G - Gubernamental"),
                        ],
                        default="V",
                        max_length=1,
                        verbose_name="tipo de documento",
                    ),
                ),
                (
                    "vat_number",
                    apps.core.fields.EncryptedCharField(
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El número de documento debe contener solo dígitos (5 a 9).",
                                regex="^\\d{5,9}$",
                            )
                        ],
                        verbose_name="número de documento",
                    ),
                ),
                (
                    "vat_hash",
                    models.CharField(
                        editable=False, max_length=64, null=True, unique=True
                    ),
                ),
                (
                    "document_photo",
                    models.FileField(
                        blank=True,
                        upload_to=apps.core.uploads.UploadTo("documents/identity"),
                        validators=[apps.core.validators.validate_document_upload],
                        verbose_name="foto del documento",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=120, verbose_name="nombres"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=120, verbose_name="apellidos"),
                ),
                (
                    "phone",
                    apps.core.fields.EncryptedCharField(
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Teléfono inválido. Ejemplo: +58 412-1234567",
                                regex="^\\+?\\d[\\d\\s-]{6,18}$",
                            )
                        ],
                        verbose_name="teléfono",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="parentesco"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "representante",
                "verbose_name_plural": "representantes",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="creado"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="activo"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=120, verbose_name="nombres"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=120, verbose_name="apellidos"),
                ),
                (
                    "phone",
                    apps.core.fields.EncryptedCharField(
                        blank=True,
                        default="",
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Teléfono inválido. Ejemplo: +58 412-1234567",
                                regex="^\\+?\\d[\\d\\s-]{6,18}$",
                            )
                        ],
                        verbose_name="teléfono",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.core.uploads.UploadTo("photos"),
                        validators=[apps.core.validators.validate_image_upload],
                        verbose_name="foto",
                    ),
                ),
                (
                    "vat_id",
                    models.CharField(
                        choices=[
                            ("V", "V - Venezolano"),
                            ("E", "E - Extranjero"),
                            ("J", "J - Jurídico"),
                            ("G", "G - Gubernamental"),
                        ],
                        default="V",
                        max_length=1,
                        verbose_name="tipo de documento",
                    ),
                ),
                (
                    "vat_hash",
                    models.CharField(
                        editable=False, max_length=64, null=True, unique=True
                    ),
                ),
                (
                    "document_photo",
                    models.FileField(
                        blank=True,
                        upload_to=apps.core.uploads.UploadTo("documents/identity"),
                        validators=[apps.core.validators.validate_document_upload],
                        verbose_name="foto del documento",
                    ),
                ),
                (
                    "document_kind",
                    models.CharField(
                        choices=[
                            ("id_card", "Cédula de identidad"),
                            ("birth_certificate", "Partida de nacimiento"),
                        ],
                        default="id_card",
                        max_length=20,
                        verbose_name="tipo de soporte",
                    ),
                ),
                (
                    "vat_number",
                    apps.core.fields.EncryptedCharField(
                        blank=True,
                        default="",
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El número de documento debe contener solo dígitos (5 a 9).",
                                regex="^\\d{5,9}$",
                            )
                        ],
                        verbose_name="número de documento",
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="fecha de nacimiento")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="players",
                        to="registry.guardian",
                        verbose_name="representante",
                    ),
                ),
            ],
            options={
                "verbose_name": "jugador",
                "verbose_name_plural": "jugadores",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Referee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="creado"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="activo"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=120, verbose_name="nombres"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=120, verbose_name="apellidos"),
                ),
                (
                    "phone",
                    apps.core.fields.EncryptedCharField(
                        blank=True,
                        default="",
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Teléfono inválido. Ejemplo: +58 412-1234567",
                                regex="^\\+?\\d[\\d\\s-]{6,18}$",
                            )
                        ],
                        verbose_name="teléfono",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.core.uploads.UploadTo("photos"),
                        validators=[apps.core.validators.validate_image_upload],
                        verbose_name="foto",
                    ),
                ),
                (
                    "vat_id",
                    models.CharField(
                        choices=[
                            ("V", "V - Venezolano"),
                            ("E", "E - Extranjero"),
                            ("J", "J - Jurídico"),
                            ("G", "G - Gubernamental"),
                        ],
                        default="V",
                        max_length=1,
                        verbose_name="tipo de documento",
                    ),
                ),
                (
                    "vat_number",
                    apps.core.fields.EncryptedCharField(
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El número de documento debe contener solo dígitos (5 a 9).",
                                regex="^\\d{5,9}$",
                            )
                        ],
                        verbose_name="número de documento",
                    ),
                ),
                (
                    "vat_hash",
                    models.CharField(
                        editable=False, max_length=64, null=True, unique=True
                    ),
                ),
                (
                    "document_photo",
                    models.FileField(
                        blank=True,
                        upload_to=apps.core.uploads.UploadTo("documents/identity"),
                        validators=[apps.core.validators.validate_document_upload],
                        verbose_name="foto del documento",
                    ),
                ),
                (
                    "license_status",
                    models.CharField(
                        choices=[
                            ("endorsed", "Avalado"),
                            ("not_endorsed", "No avalado"),
                        ],
                        default="not_endorsed",
                        max_length=20,
                        verbose_name="licencia",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referee_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "árbitro",
                "verbose_name_plural": "árbitros",
                "ordering": ["last_name", "first_name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="creado"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="activo"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Venezuela", max_length=80, verbose_name="país"
                    ),
                ),
                ("state", models.CharField(max_length=80, verbose_name="estado")),
                (
                    "municipality",
                    models.CharField(max_length=120, verbose_name="municipio"),
                ),
                ("address", models.CharField(max_length=255, verbose_name="dirección")),
                (
                    "vat_id",
                    models.CharField(
                        choices=[
                            ("V", "V - Venezolano"),
                            ("E", "E - Extranjero"),
                            ("J", "J - Jurídico"),
                            ("G", "G - Gubernamental"),
                        ],
                        default="V",
                        max_length=1,
                        verbose_name="tipo de documento",
                    ),
                ),
                (
                    "vat_number",
                    apps.core.fields.EncryptedCharField(
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El número de documento debe contener solo dígitos (5 a 9).",
                                regex="^\\d{5,9}$",
                            )
                        ],
                        verbose_name="número de documento",
                    ),
                ),
                (
                    "vat_hash",
                    models.CharField(
                        editable=False, max_length=64, null=True, unique=True
                    ),
                ),
                (
                    "document_photo",
                    models.FileField(
                        blank=True,
                        upload_to=apps.core.uploads.UploadTo("documents/identity"),
                        validators=[apps.core.validators.validate_document_upload],
                        verbose_name="foto del documento",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="nombre"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.core.uploads.UploadTo("logos/teams"),
                        validators=[apps.core.validators.validate_image_upload],
                        verbose_name="logo",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="teams",
                        to="registry.category",
                        verbose_name="categorías",
                    ),
                ),
                (
                    "coaches",
                    models.ManyToManyField(
                        blank=True,
                        related_name="teams",
                        to="registry.coach",
                        verbose_name="entrenadores",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "home_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teams",
                        to="registry.field",
                        verbose_name="cancha",
                    ),
                ),
                (
                    "managers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="managed_teams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="gestores",
                    ),
                ),
            ],
            options={
                "verbose_name": "equipo",
                "verbose_name_plural": "equipos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TeamPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="creado"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="activo"
                    ),
                ),
                (
                    "shirt_number",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(99)],
                        verbose_name="dorsal",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="registry.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="registry.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roster",
                        to="registry.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "jugador en nómina",
                "verbose_name_plural": "nómina de jugadores",
                "ordering": ["team", "category", "shirt_number"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("player", "category"),
                        name="unique_active_player_category",
                    )
                ],
            },
        ),
    ]
