# Generated by Django 5.2.18 on 2026-10-09 19:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teamplayer',
            name='unique_active_player_category',
        ),
        migrations.RemoveField(
            model_name='teamplayer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='teamplayer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='teamplayer',
            name='player',
        ),
        migrations.RemoveField(
            model_name='teamplayer',
            name='team',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['max_age', 'name'], 'verbose_name': 'categoría', 'verbose_name_plural': 'categorías'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='birth_year_limit',
        ),
        migrations.RemoveField(
            model_name='team',
            name='coaches',
        ),
        migrations.AddField(
            model_name='coach',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaches', to='registry.team', verbose_name='equipo'),
        ),
        migrations.AddField(
            model_name='coach',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coach_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='player',
            name='current_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_players', to='registry.team', verbose_name='equipo actual'),
        ),
        migrations.AlterField(
            model_name='category',
            name='max_age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='tope de edad'),
        ),
    ]
