# Generated by Django 5.2.18 on 2026-10-09 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_alter_lineupplayer_team_player_and_more'),
        ('registry', '0002_squad_rules'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamPlayer',
        ),
    ]
