# Generated by Django 5.2.18 on 2026-10-09 15:34

import apps.core.uploads
import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("registry", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="creado"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="activo"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="nombre"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.core.uploads.UploadTo("logos/tournaments"),
                        validators=[apps.core.validators.validate_image_upload],
                        verbose_name="logo",
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("league", "Liga (todos contra todos)"),
                            ("league_double", "Liga ida y vuelta"),
                            ("groups", "Fase de grupos"),
                            ("groups_knockout", "Grupos + eliminación directa"),
                            ("knockout", "Eliminación directa"),
                        ],
                        default="league",
                        max_length=20,
                        verbose_name="modalidad",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("registration", "Inscripciones"),
                            ("in_progress", "En curso"),
                            ("finished", "Finalizado"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de inicio"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de fin"
                    ),
                ),
                (
                    "match_duration_minutes",
                    models.PositiveSmallIntegerField(
                        default=60,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(150),
                        ],
                        verbose_name="duración del partido (min)",
                    ),
                ),
                (
                    "periods",
                    models.PositiveSmallIntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="tiempos",
                    ),
                ),
                (
                    "break_minutes",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="descanso (min)"
                    ),
                ),
                (
                    "max_substitutions",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Vacío = ilimitados",
                        null=True,
                        verbose_name="cambios máximos",
                    ),
                ),
                (
                    "max_lineup_players",
                    models.PositiveSmallIntegerField(
                        default=18, verbose_name="jugadores por planilla"
                    ),
                ),
                (
                    "starters_count",
                    models.PositiveSmallIntegerField(
                        default=11, verbose_name="titulares"
                    ),
                ),
                (
                    "referees_required",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                        verbose_name="árbitros requeridos (terna)",
                    ),
                ),
                (
                    "points_win",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="puntos por victoria"
                    ),
                ),
                (
                    "points_draw",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="puntos por empate"
                    ),
                ),
                (
                    "points_loss",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="puntos por derrota"
                    ),
                ),
                (
                    "regulation_text",
                    models.TextField(blank=True, verbose_name="reglamento (texto)"),
                ),
                (
                    "regulation_file",
                    models.FileField(
                        blank=True,
                        upload_to=apps.core.uploads.UploadTo("tournaments/regulations"),
                        validators=[apps.core.validators.validate_document_upload],
                        verbose_name="reglamento (archivo)",
                    ),
                ),
                (
                    "lineup_sheet_file",
                    models.FileField(
                        blank=True,
                        upload_to=apps.core.uploads.UploadTo("tournaments/templates"),
                        validators=[apps.core.validators.validate_document_upload],
                        verbose_name="planilla de alineación (plantilla)",
                    ),
                ),
                (
                    "substitution_card_file",
                    models.FileField(
                        blank=True,
                        upload_to=apps.core.uploads.UploadTo("tournaments/templates"),
                        validators=[apps.core.validators.validate_document_upload],
                        verbose_name="tarjeta de cambio (plantilla)",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="tournaments",
                        to="registry.category",
                        verbose_name="categorías permitidas",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "fields",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tournaments",
                        to="registry.field",
                        verbose_name="canchas disponibles",
                    ),
                ),
            ],
            options={
                "verbose_name": "torneo",
                "verbose_name_plural": "torneos",
                "ordering": ["-start_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="creado"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="activo"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ej.: Grupo A", max_length=40, verbose_name="nombre"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="registry.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="groups",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "grupo",
                "verbose_name_plural": "grupos",
                "ordering": ["tournament", "category", "name"],
            },
        ),
        migrations.CreateModel(
            name="TournamentTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="creado"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="activo"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="registry.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teams",
                        to="tournaments.group",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="registry.team",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "equipo inscrito",
                "verbose_name_plural": "equipos inscritos",
                "ordering": ["tournament", "category", "team__name"],
            },
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                fields=("tournament", "category", "name"), name="unique_group_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="tournamentteam",
            constraint=models.UniqueConstraint(
                fields=("tournament", "team", "category"), name="unique_registration"
            ),
        ),
    ]
