# Generated by Django 5.2.18 on 2026-10-09 19:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from apps.core.db import enable_row_level_security


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_squad_rules'),
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='activo')),
                ('shirt_number', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='dorsal')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='registry.player', verbose_name='jugador')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roster', to='tournaments.tournamentteam', verbose_name='inscripción')),
                ('tournament', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='roster', to='tournaments.tournament', verbose_name='torneo')),
            ],
            options={
                'verbose_name': 'jugador en nómina',
                'verbose_name_plural': 'nómina de jugadores',
                'ordering': ['registration', 'shirt_number'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tournament', 'player'), name='unique_active_player_per_tournament'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('registration', 'shirt_number'), name='unique_active_shirt_per_registration')],
            },
        ),
        # RLS también en la tabla nueva (bloquea la API REST pública de Supabase).
        migrations.RunPython(enable_row_level_security, migrations.RunPython.noop),
    ]
