# Generated by Django 5.2.18 on 2026-10-09 15:34

import apps.core.uploads
import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("registry", "0001_initial"),
        ("tournaments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="creado"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "round_number",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="fecha / ronda"
                    ),
                ),
                (
                    "sub_field",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="mini cancha"
                    ),
                ),
                (
                    "scheduled_start",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="inicio programado",
                    ),
                ),
                (
                    "scheduled_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fin programado"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("pending", "Pendiente de confirmación"),
                            ("confirmed", "Confirmado"),
                            ("in_progress", "En juego"),
                            ("finished", "Finalizado (informes pendientes)"),
                            ("closed", "Cerrado"),
                            ("suspended", "Suspendido"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("not_started", "Por iniciar"),
                            ("playing", "En juego"),
                            ("break", "Descanso"),
                            ("ended", "Terminado"),
                        ],
                        default="not_started",
                        max_length=12,
                    ),
                ),
                ("current_period", models.PositiveSmallIntegerField(default=0)),
                ("period_started_at", models.DateTimeField(blank=True, null=True)),
                ("assignment_version", models.PositiveIntegerField(default=1)),
                ("home_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("away_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "assistant_referee_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches_as_assistant_1",
                        to="registry.referee",
                    ),
                ),
                (
                    "assistant_referee_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches_as_assistant_2",
                        to="registry.referee",
                    ),
                ),
                (
                    "away",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="away_matches",
                        to="tournaments.tournamentteam",
                        verbose_name="visitante",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="registry.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delegate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches",
                        to="registry.delegate",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches",
                        to="registry.field",
                        verbose_name="cancha",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches",
                        to="tournaments.group",
                    ),
                ),
                (
                    "home",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="home_matches",
                        to="tournaments.tournamentteam",
                        verbose_name="local",
                    ),
                ),
                (
                    "referee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches_as_referee",
                        to="registry.referee",
                        verbose_name="árbitro principal",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "partido",
                "verbose_name_plural": "partidos",
                "ordering": ["scheduled_start", "id"],
                "permissions": [
                    (
                        "schedule_match",
                        "Puede programar partidos (cancha, horario, oficiales)",
                    ),
                    ("generate_fixture", "Puede generar el fixture"),
                    (
                        "adjust_match",
                        "Puede ajustar partidos confirmados con exposición de motivos",
                    ),
                    ("confirm_assignment", "Puede confirmar o rechazar su asignación"),
                    ("operate_match", "Puede operar la mesa técnica de sus partidos"),
                    (
                        "operate_any_match",
                        "Puede operar la mesa técnica de cualquier partido",
                    ),
                    ("submit_lineup", "Puede cargar alineaciones de sus equipos"),
                    (
                        "verify_lineup",
                        "Puede verificar documentación/alineaciones en mesa técnica",
                    ),
                    ("submit_delegate_report", "Puede enviar el informe del delegado"),
                    ("submit_referee_report", "Puede enviar el informe arbitral"),
                    ("return_report", "Puede devolver informes para corrección"),
                    ("close_match", "Puede cerrar partidos"),
                    ("suspend_match", "Puede suspender partidos"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Lineup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="creado"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Cargada"),
                            ("verified", "Verificada en mesa técnica"),
                        ],
                        default="submitted",
                        max_length=10,
                    ),
                ),
                (
                    "sheet_file",
                    models.FileField(
                        blank=True,
                        upload_to=apps.core.uploads.UploadTo("lineups"),
                        validators=[apps.core.validators.validate_document_upload],
                        verbose_name="planilla firmada",
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "coach",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="registry.coach",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lineups",
                        to="tournaments.tournamentteam",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lineups",
                        to="competition.match",
                    ),
                ),
            ],
            options={
                "verbose_name": "alineación",
                "verbose_name_plural": "alineaciones",
            },
        ),
        migrations.CreateModel(
            name="MatchAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="registrado"
                    ),
                ),
                ("version_from", models.PositiveIntegerField()),
                ("version_to", models.PositiveIntegerField()),
                ("changes", models.JSONField(default=dict)),
                ("affected_parties", models.JSONField(default=list)),
                ("reason", models.TextField(verbose_name="exposición de motivos")),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="competition.match",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ajuste de partido",
                "verbose_name_plural": "ajustes de partidos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="registrado"
                    ),
                ),
                ("assignment_version", models.PositiveIntegerField()),
                (
                    "party",
                    models.CharField(
                        choices=[
                            ("delegate", "Delegado"),
                            ("referee", "Árbitro principal"),
                            ("assistant_1", "Árbitro asistente 1"),
                            ("assistant_2", "Árbitro asistente 2"),
                            ("home", "Equipo local"),
                            ("away", "Equipo visitante"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "response",
                    models.CharField(
                        choices=[("accepted", "Confirmado"), ("rejected", "Rechazado")],
                        max_length=10,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmations",
                        to="competition.match",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "confirmación de asistencia",
                "verbose_name_plural": "confirmaciones de asistencia",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Matchday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="creado"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(verbose_name="número de jornada"),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=120, verbose_name="nombre"),
                ),
                ("date", models.DateField(verbose_name="día de jornada")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("submitted", "Enviada (pendiente de confirmaciones)"),
                            ("confirmed", "Válida (confirmada)"),
                            ("closed", "Cerrada"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matchdays",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "jornada",
                "verbose_name_plural": "jornadas",
                "ordering": ["tournament", "number"],
                "permissions": [
                    ("submit_matchday", "Puede enviar jornadas a confirmación"),
                    ("close_matchday", "Puede cerrar jornadas"),
                ],
            },
        ),
        migrations.AddField(
            model_name="match",
            name="matchday",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matches",
                to="competition.matchday",
            ),
        ),
        migrations.CreateModel(
            name="MatchEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="registrado"
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("delegate_arrival", "Llegada del delegado"),
                            ("team_arrival", "Llegada de equipo"),
                            ("documents_verified", "Documentación verificada"),
                            ("kickoff", "Inicio del partido"),
                            ("period_start", "Inicio de tiempo"),
                            ("goal", "Gol"),
                            ("penalty_goal", "Gol de penal"),
                            ("own_goal", "Autogol"),
                            ("yellow_card", "Tarjeta amarilla"),
                            ("red_card", "Tarjeta roja"),
                            ("substitution", "Cambio"),
                            ("incident", "Incidencia"),
                            ("period_end", "Fin de tiempo"),
                            ("match_end", "Fin del partido"),
                            ("annulment", "Anulación de evento"),
                            ("note", "Nota"),
                        ],
                        max_length=20,
                    ),
                ),
                ("period", models.PositiveSmallIntegerField(default=0)),
                ("minute", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "annuls",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="annulled_by",
                        to="competition.matchevent",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="competition.match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="registry.teamplayer",
                    ),
                ),
                (
                    "player_in",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="registry.teamplayer",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tournaments.tournamentteam",
                    ),
                ),
            ],
            options={
                "verbose_name": "evento de partido",
                "verbose_name_plural": "eventos de partido",
                "ordering": ["match", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="MatchNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="registrado"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("note", "Nota"), ("appeal", "Apelación")],
                        default="note",
                        max_length=10,
                    ),
                ),
                ("body", models.TextField()),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        upload_to=apps.core.uploads.UploadTo("notes"),
                        validators=[apps.core.validators.validate_document_upload],
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notes",
                        to="competition.match",
                    ),
                ),
            ],
            options={
                "verbose_name": "nota / apelación",
                "verbose_name_plural": "notas y apelaciones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="registrado"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("delegate", "Delegado"), ("referee", "Árbitro")],
                        max_length=10,
                    ),
                ),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("home_score", models.PositiveSmallIntegerField()),
                ("away_score", models.PositiveSmallIntegerField()),
                ("home_yellow", models.PositiveSmallIntegerField(default=0)),
                ("away_yellow", models.PositiveSmallIntegerField(default=0)),
                ("home_red", models.PositiveSmallIntegerField(default=0)),
                ("away_red", models.PositiveSmallIntegerField(default=0)),
                ("observations", models.TextField(blank=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        upload_to=apps.core.uploads.UploadTo("reports"),
                        validators=[apps.core.validators.validate_document_upload],
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="competition.match",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "informe de partido",
                "verbose_name_plural": "informes de partido",
                "ordering": ["match", "role", "-version"],
            },
        ),
        migrations.CreateModel(
            name="MatchClosure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="registrado"
                    ),
                ),
                ("home_score", models.PositiveSmallIntegerField()),
                ("away_score", models.PositiveSmallIntegerField()),
                ("notes", models.TextField(blank=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="closure",
                        to="competition.match",
                    ),
                ),
                (
                    "delegate_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="competition.matchreport",
                    ),
                ),
                (
                    "referee_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="competition.matchreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "cierre de partido",
                "verbose_name_plural": "cierres de partidos",
            },
        ),
        migrations.CreateModel(
            name="ReportReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="registrado"
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returned",
                        to="competition.matchreport",
                    ),
                ),
                (
                    "returned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "devolución de informe",
                "verbose_name_plural": "devoluciones de informes",
            },
        ),
        migrations.CreateModel(
            name="ReviewCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="creado"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("rejection", "Rechazo de asignación"),
                            ("appeal", "Apelación"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Abierto"),
                            ("resolved", "Resuelto"),
                            ("dismissed", "Desestimado"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=10,
                    ),
                ),
                ("reason", models.TextField()),
                ("resolution", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="competition.matchconfirmation",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_cases",
                        to="competition.match",
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="competition.matchnote",
                    ),
                ),
                (
                    "raised_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "caso en revisión",
                "verbose_name_plural": "casos en revisión",
                "ordering": ["status", "-created_at"],
                "permissions": [
                    ("resolve_reviewcase", "Puede resolver casos en revisión")
                ],
            },
        ),
        migrations.CreateModel(
            name="LineupPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shirt_number",
                    models.PositiveSmallIntegerField(verbose_name="dorsal"),
                ),
                (
                    "is_starter",
                    models.BooleanField(default=False, verbose_name="titular"),
                ),
                (
                    "is_captain",
                    models.BooleanField(default=False, verbose_name="capitán"),
                ),
                (
                    "lineup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="competition.lineup",
                    ),
                ),
                (
                    "team_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="registry.teamplayer",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_starter", "shirt_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lineup", "team_player"), name="unique_lineup_player"
                    ),
                    models.UniqueConstraint(
                        fields=("lineup", "shirt_number"), name="unique_lineup_shirt"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="lineup",
            constraint=models.UniqueConstraint(
                fields=("match", "team"), name="unique_lineup_per_team"
            ),
        ),
        migrations.AddConstraint(
            model_name="matchday",
            constraint=models.UniqueConstraint(
                fields=("tournament", "number"), name="unique_matchday_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="matchevent",
            constraint=models.UniqueConstraint(
                fields=("match", "sequence"), name="unique_event_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="matchreport",
            constraint=models.UniqueConstraint(
                fields=("match", "role", "version"), name="unique_report_version"
            ),
        ),
    ]
