# Generated by Django 5.2.18 on 2026-10-09 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_database_protections'),
        ('tournaments', '0002_teamplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineupplayer',
            name='team_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tournaments.teamplayer'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tournaments.teamplayer'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='player_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tournaments.teamplayer'),
        ),
    ]
