# Generated by Django 5.2.18 on 2026-10-09 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_alter_lineupplayer_team_player_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineupplayer',
            options={'ordering': ['-is_starter', 'shirt_number'], 'verbose_name': 'jugador en alineación', 'verbose_name_plural': 'jugadores en alineación'},
        ),
    ]
